import "server-only"

import { getGeminiClient } from "@/lib/gemini/client"

// ─── Image model ──────────────────────────────────────────────────────────────
// The env var DEFAULT_IMAGE_MODEL overrides the constant below.
// Keep the constant here so the model name is changed in exactly one place.
//
// Gemini native image generation uses the gemini-2.0-flash-preview-image-generation
// model via responseModalities: ["IMAGE"]. The env var lets the team switch
// to a newer model without a code deploy.

export const DEFAULT_IMAGE_MODEL_NAME = "gemini-2.0-flash-preview-image-generation"

export function resolveImageModel(): string {
  return process.env.DEFAULT_IMAGE_MODEL ?? DEFAULT_IMAGE_MODEL_NAME
}

// ─── Visual type ──────────────────────────────────────────────────────────────

export type VisualType =
  | "editorial_cover"
  | "infographic"
  | "quote_card"
  | "concept_diagram"
  | "chart_visual"

/**
 * Analyse post content and select the most appropriate visual type.
 *
 * Rules (in order of priority):
 *   1. interview → quote_card  (personal quotes are the natural visual)
 *   2. process/framework/steps keywords → infographic
 *   3. system/architecture/layers keywords → concept_diagram
 *   4. real numeric patterns (%, $, Nx) → chart_visual
 *   5. default → editorial_cover
 *
 * chart_visual is only chosen when the text contains clear numeric evidence
 * (percentages, dollar amounts, multipliers). This prevents fabricated charts.
 */
export function selectVisualType(opts: {
  contentType: string
  title:       string
  excerpt:     string
  body:        string
}): VisualType {
  const { contentType, title, excerpt, body } = opts

  // Interview → quote_card
  if (contentType === "interview") return "quote_card"

  const haystack = [title, excerpt, body.slice(0, 2000)].join(" ")

  // Process / steps / framework → infographic
  if (/\b(steps?|stages?|phases?|framework|process|methodology|roadmap|playbook|guide|how to|workflow|checklist)\b/i.test(haystack)) {
    return "infographic"
  }

  // Structural / system concepts → concept_diagram
  if (/\b(ecosystem|architecture|model|system|hierarchy|layers?|components?|pillars?|stack|platform|infrastructure)\b/i.test(haystack)) {
    return "concept_diagram"
  }

  // Real numeric data → chart_visual (only strong patterns — avoids years/IDs)
  if (/(\d+(?:\.\d+)?%|\$\d+[BMK]?|\d+(?:\.\d+)?x\b|\d+ (?:companies|organizations|businesses|respondents|executives|firms|leaders))/i.test(haystack)) {
    return "chart_visual"
  }

  return "editorial_cover"
}

// ─── Prompt builder ───────────────────────────────────────────────────────────
//
// IMPORTANT — text-free rule for AI providers (Replicate + Gemini):
// AI image models cannot reliably render readable text. Attempting to do so
// produces distorted letters, gibberish, or fake UI elements that look bad.
// All prompts MUST be text-free. Title and excerpt appear in the article
// page, Telegram caption, and LinkedIn post text — not in the image.
//
// SVG fallback is generated by code and renders crisp text intentionally.

// Max body snippet used only as thematic context — never rendered into image.
const MAX_BODY_SNIPPET = 400

// ── Style requirements applied to every AI-generated image ────────────────────
const STYLE_GUIDE = [
  "premium business editorial visual",
  "very dark background (#0a0a0a to #1c1c1c)",
  "gold/amber accent color (#f59e0b) with white geometric highlights",
  "clean minimal composition",
  "high contrast",
  "subtle gradients and depth",
  "no realistic human faces or portraits",
  "no copyrighted logos, wordmarks, or brand names",
  "editorial illustration style suitable for a business intelligence publication",
  "16:9 widescreen aspect ratio",
].join(", ")

// ── Absolute text prohibition — appended to every AI prompt ──────────────────
// Listed explicitly because AI models need to be told this clearly and repeatedly.
const NO_TEXT_RULE =
  "CRITICAL RULE — THE IMAGE MUST CONTAIN ZERO TEXT:\n" +
  "• No letters, words, sentences, or phrases of any kind\n" +
  "• No numbers, digits, percentages, or numeric labels\n" +
  "• No axis labels, chart annotations, or data callouts\n" +
  "• No typography, fonts, or rendered glyphs\n" +
  "• No UI labels, button text, or interface copy\n" +
  "• No logos, wordmarks, or brand names\n" +
  "• No watermarks, captions, or credit text\n" +
  "• No random symbols, dashes used as text, or gibberish characters\n" +
  "• No speech bubbles, quote marks rendered as text, or annotation boxes\n" +
  "The image is a pure abstract visual composition. All textual content " +
  "will be added separately in the article page, Telegram caption, and LinkedIn post."

// ── Per-visual-type instructions ──────────────────────────────────────────────
// Context (topic) is used for thematic direction only — never to render text.

type PromptContext = { topic: string }

const TYPE_INSTRUCTIONS: Record<VisualType, (ctx: PromptContext) => string> = {
  editorial_cover: ({ topic }) =>
    `Abstract editorial cover illustration for a business article about ${topic}. ` +
    `Use flowing geometric shapes, luminous data glyphs, circuit-like line patterns, ` +
    `or conceptual metaphors that evoke strategy, intelligence, and innovation. ` +
    `Dark atmospheric composition with amber/gold accent light sources. ` +
    `Purely abstract — no literal objects or scenes. No text of any kind.`,

  infographic: ({ topic }) =>
    `Abstract process-flow illustration representing a business framework about ${topic}. ` +
    `Show 3–5 connected abstract steps using geometric blocks, directional arrows, ` +
    `and flow lines. Use simple icon-like silhouettes (circles, hexagons, chevrons). ` +
    `No text, no labels, no numbers inside the shapes — shapes only. ` +
    `Dark background with amber accent connections.`,

  quote_card: ({ topic }) =>
    `Abstract editorial portrait-free visual for a business interview about ${topic}. ` +
    `Evoke thought leadership and insight through converging geometric forms, ` +
    `subtle radial light gradients, and layered abstract planes. ` +
    `Use a large amber/gold accent shape as a focal point. ` +
    `Atmospheric and contemplative mood. No text, no quotation marks, no typography.`,

  concept_diagram: ({ topic }) =>
    `Abstract system architecture or ecosystem diagram for a ${topic} concept. ` +
    `Show interconnected nodes, layered planes, or component clusters using ` +
    `geometric shapes (circles, hexagons, rectangles) with fine connecting lines. ` +
    `Suggest hierarchy and relationship without any labels. ` +
    `Dark background, amber/white node highlights. No text, no numbers, no annotations.`,

  chart_visual: ({ topic }) =>
    `Abstract data visualisation representing growth or trend patterns in ${topic}. ` +
    `Use stylised bar, line, or area chart silhouettes as pure decorative shapes. ` +
    `The chart forms are visual texture — not real data. ` +
    `No axis lines with labels, no tick marks, no data callouts, no numbers. ` +
    `Dark editorial aesthetic with amber accent on the chart shapes.`,
}

export function buildImagePrompt(opts: {
  title:       string
  excerpt:     string
  body:        string
  topic:       string
  contentType: string
  visualType:  VisualType
}): string {
  const { body, topic, visualType } = opts

  // Body snippet is thematic context only — the AI must not render it as text.
  const bodySnippet = body.slice(0, MAX_BODY_SNIPPET)
  const typeInstruction = TYPE_INSTRUCTIONS[visualType]({ topic })

  return (
    `Generate a single high-quality cover image for a business publication.\n\n` +
    `Visual type: ${visualType}\n` +
    `Topic area: ${topic}\n\n` +
    `${typeInstruction}\n\n` +
    `Thematic context (for inspiration only — do NOT render as text):\n${bodySnippet}\n\n` +
    `Style requirements: ${STYLE_GUIDE}\n\n` +
    `${NO_TEXT_RULE}\n\n` +
    `Output: one image only. No explanation, no markdown, just the image.`
  )
}

// ─── Image generation result ──────────────────────────────────────────────────

export type ImageGenerationResult = {
  base64:     string   // raw base64, no data URI prefix
  mimeType:   string   // e.g. "image/png"
  visualType: VisualType
}

// ─── Main generator ───────────────────────────────────────────────────────────

/**
 * Generate a cover image for a post using Gemini's native image output.
 *
 * 1. Selects the visual type from post content.
 * 2. Builds a prompt.
 * 3. Calls Gemini with responseModalities: ["IMAGE"].
 * 4. Returns the raw base64 image bytes + mime type.
 *
 * Throws on any failure — caller is responsible for error handling.
 */
export async function generateCoverImage(opts: {
  title:       string
  excerpt:     string
  body:        string
  topic:       string
  contentType: string
}): Promise<ImageGenerationResult> {
  const model = resolveImageModel()

  if (!process.env.GEMINI_API_KEY) {
    throw new Error("[image] GEMINI_API_KEY is not set.")
  }
  if (!process.env.DEFAULT_IMAGE_MODEL && model === DEFAULT_IMAGE_MODEL_NAME) {
    // DEFAULT_IMAGE_MODEL not set — using hardcoded default, which is fine.
    // Just log so it's discoverable in dev.
    console.log(`[image] DEFAULT_IMAGE_MODEL not set, using built-in default: ${DEFAULT_IMAGE_MODEL_NAME}`)
  }

  const visualType = selectVisualType({
    contentType: opts.contentType,
    title:       opts.title,
    excerpt:     opts.excerpt,
    body:        opts.body,
  })

  const prompt = buildImagePrompt({ ...opts, visualType })

  const ai = getGeminiClient()

  console.log(`[image] generating cover — model=${model} visualType=${visualType}`)

  const response = await ai.models.generateContent({
    model,
    contents: [
      {
        role:  "user",
        parts: [{ text: prompt }],
      },
    ],
    config: {
      // Request image output from the model.
      // Some Gemini versions use "IMAGE", others need the full mime type.
      responseModalities: ["IMAGE"],
    },
  })

  // Extract image inline data from the response parts
  const parts = response.candidates?.[0]?.content?.parts ?? []
  for (const part of parts) {
    const inlineData = part.inlineData as { data: string; mimeType: string } | undefined
    if (inlineData?.data) {
      return {
        base64:     inlineData.data,
        mimeType:   inlineData.mimeType ?? "image/png",
        visualType,
      }
    }
  }

  // If we reach here the model returned no image
  throw new Error(
    `[image] Gemini returned no image data for model ${model}. ` +
    `Response text: ${(response.text ?? "").slice(0, 200)}`,
  )
}
