-- =============================================================================
-- 004_post_images_bucket.sql
-- BizInsight — post-images Storage bucket (manual setup required)
-- =============================================================================
--
-- THIS MIGRATION CONTAINS NO EXECUTABLE SQL.
--
-- Supabase-managed storage tables (storage.buckets, storage.objects) require
-- table ownership to create policies or insert bucket records. The project
-- role does not have that privilege, so any SQL targeting those tables will
-- fail with: ERROR 42501: must be owner of relation objects / table buckets.
--
-- MANUAL SETUP (one-time, required before the image generation feature works)
-- ---------------------------------------------------------------------------
-- Create the bucket in Supabase Dashboard → Storage → New bucket:
--
--   Name:               post-images
--   Public bucket:      ON    ← required so cover image URLs load on the site
--   File size limit:    5 MB
--   Allowed MIME types: image/png, image/jpeg, image/webp
--
-- That is all. No SQL needs to be run.
--
-- WHY NO RLS POLICY IS NEEDED
-- ----------------------------
-- • Reads  — the bucket is public, so images are accessible by URL without
--             any policy. No anon SELECT policy is required.
-- • Writes — uploads go through the server-side service role client
--             (SUPABASE_SERVICE_ROLE_KEY), which bypasses RLS entirely.
--             No INSERT/UPDATE/DELETE policy is required.
-- • Browser uploads — not supported. All image generation is server-side.
--
-- PATH CONVENTION
-- ----------------
-- posts/{postId}/cover-{timestamp}.{ext}
-- Example: posts/9f1a2b3c-…/cover-1716400000000.png
--
-- VERIFICATION (run manually in SQL Editor after creating the bucket)
-- -------------------------------------------------------------------
--   SELECT id, name, public FROM storage.buckets WHERE id = 'post-images';
--
-- Expected row: id=post-images | name=post-images | public=true
-- =============================================================================
